[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/NODEFAULTLIB:msvcrt.lib",
    "-C", "link-arg=/DEFAULTLIB:libcmt.lib",
]

[env]
VCPKG_DEFAULT_TRIPLET = "x64-windows-static"
VCPKG_ROOT = "C:\vcpkg"